"""Shared region configuration for the data pipeline.

Single source of truth for which municipalities and Overpass bounding boxes
belong to each of Finland's 69 seutukunnat (sub-regions). The two config files
read here are generated by scripts/build_seutukunta_boundaries.mjs from the
canonical scripts/seutukunnat.json, and match src/utils/regions.ts.

Every fetch_*.py script should import region config from this module instead
of hardcoding its own metro-area municipality / bbox lists.
"""
import json
from pathlib import Path

_DIR = Path(__file__).parent

with open(_DIR / "seutukunta_municipalities.json", encoding="utf-8") as _f:
    # region id (e.g. "helsinki_metro", "oulu", "loimaa") -> set of muni codes
    REGION_MUNICIPALITY_CODES = {
        region_id: set(codes) for region_id, codes in json.load(_f).items()
    }

with open(_DIR / "seutukunta_bboxes.json", encoding="utf-8") as _f:
    # region id -> Overpass bbox string "south,west,north,east"
    REGION_BBOXES = json.load(_f)

# Flattened municipality code -> region id
MUNICIPALITY_CITY = {
    code: region
    for region, codes in REGION_MUNICIPALITY_CODES.items()
    for code in codes
}

# All municipality codes across all regions (308)
ALL_MUNICIPALITY_CODES = set(MUNICIPALITY_CITY.keys())

# All Overpass bboxes, one per region (69)
ALL_BBOXES = list(REGION_BBOXES.values())

# Finnish municipality name -> 3-digit code, for data sources (e.g. Traficom)
# that key their data by municipality name rather than code.
with open(_DIR / "seutukunnat.json", encoding="utf-8") as _f:
    MUNICIPALITY_NAME_TO_CODE = {
        name: code
        for _s in json.load(_f)["seutukunnat"]
        for code, name in zip(_s["municipality_codes"], _s["municipality_names_fi"])
    }
